### ISSUE TITLE
Todo 완료 기능 구현하기

### ISSUE THREAD

**Issue by hurima90-kim** [hurima90-kim/SolarConnect_Todo#2]
- [ ] Todo 완료 기능 구현
- [ ] onClick 이벤트 연결
- [ ] 완료시 CSS 변경 적용
